### PR TITLE
Update poseeditor.cpp

### PR DESCRIPTION
**Pull request by henrycddj**
Record their values before you change them otherwise you won't update them if you just change the rotation

### CODE REVIEW

**Comment by florianblume** [comment]
Hey thanks @henrycddj for your pull request! Love to see that someone is helping to make the program better. At some point I must have broken the rotation editing without noticing. I was doing some major refactoring to fix this and some other bugs. Next thing I want to implement are some tests to keep the program from breaking.

**Comment by henrycddj** [comment]
Thank you. I am happy to do something for this project.

**Comment by florianblume** [comment]
I'll try to create a new release as soon as possible, right now the changes are only on the master.

**Comment by henrycddj** [comment]
In fact, I am trying to modify the code to get all the coordinates of the model on the picture pixels. But I am not familiar with QT3d/opengl, can I modify the PoseViewer3DWidget to achieve my purpose?

**Comment by florianblume** [comment]
I'm not sure I understand what you want to achieve. Could you open a new issue and post some more details?

**Pull request merged**
